version: '3.8'

services:
  backend:
    image: hello-backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
    container_name: backend
  frontend:
    image: hello-frontend
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    container_name: frontend
  redis:
    image: redis
  
